char0n/ramda-adjunct

src/index.d.ts
It's probably a typo in the definition, probably the inconsistency has been introduced recently in the typescript side.
In the current stable Typescript the javascript `boolean` type is defined with lower case letters, the current definition is apparently referencing a global interface: https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#322-the-boolean-type
=> Typescript `boolean` is not `Boolean`

src/index.d.ts
also fixed this cases for `concatRight`
```ts
// not right behavior 
const add = RA.concatRight(':') // => (secondList:·":")·=>·":"
const added = add('asdfasdf') // => ":"
// right behavior 
const add = RA.concatRight([1]) // => (secondList:·number[])·=>·number[]
const added = add([2]) // => number[]
// not right behavior 
const added = RA.concatRight('asdf', 'we') // => "asdf" | "we"
```
now when parameter is string - string returned
=> Fix/missed types + typings for contatRight

src/index.d.ts, src/index.js, src/isFalsy.js, src/isTruthy.js, test/isFalsy.js
=> feat: add isFalsy

package.json
For the following reasons:
- The use of es6 esports in the referenced file caused an RTE in Webpack v1.x because it doesn’t transpile code from node modules.
- The use of the `browser` field in package.json was superfluous as it pointed to the same file as `module`. The purpose of the `browser` field is to provide code that is specific to a browser (for example it uses polyfills or shims), but that is not relevant for this lib at present. For spec of `browser` field see: https://github.com/defunctzombie/package-browser-field-spec
See: #242
=> build(npm) Remove module field from package.json

src/fantasy-land/Identity.js
Corrects a minor typo in the Identity equals documentation.
=> Typo in docs

package.json, src/index.d.ts, src/index.js, src/notBoth.js, test/notBoth.js
Add `notBoth` function which is complement of Ramda's `both`.
- I've kept the docs close to Ramda's docs for `both`.
- I've assumed the next release will be 2.3.0.
- I've had to add Sanctuary as a dev dependency to replicate the fantasy-land tests.
- I'll add the other complements in separate PRs once this one is approved.
Ref #234
=> feat(api): add notBoth function

src/index.d.ts, src/index.js, src/isEmptyArray.js, test/isEmptyArray.js
=> feat: add isEmptyArray

src/index.d.ts, src/index.js, src/notAllPass.js, test/notAllPass.js
Because of the auto-currying I had to use Ramda's implementation of `allPass`, but tweaked to return the correct result and to satisfy eslint.
Ref #234
=> feat(notAllPass): Add notAllPass which is the complement of allPass

package.json
This script is useful before a push.
-----------
Every time I push, I like to check if all is good using : 
```bash
$ npm run clean && npm run lint && npm run test && npm run test:web && npm run build
```
What do you think about a `test:all` npm script ?
=> chore(scripts): improve prepublishOnly

package.json
Because sometimes I like to `npm run build:umd && npm run docs` and build seems faster with progress bar
=> chore(webpack): display progress on build:umd

.commitlintrc.json, package.json, scripts/pre-commit.sh
Resolves #381.
Resolves #386.
All the hooks we discussed, everything I came up with.
Every hook is added in a separate commit, so to not add a hook, just reverting a commit.
I suggest merge-squashing it after we're done, one `chore(package): added git hooks` would be completely fine IMO.
~~I think that push hook unnecessarily builds the project twice, one for testing, one for build. If that's the case, then `bnr build` in `prepush` is just wasting time. (It is there in the first place because of https://github.com/char0n/ramda-adjunct/issues/381#issuecomment-366826618)~~
`npm run build` creates 3 builds. Trying to build just one just to see if it succeeds would probably suffice on pre-push, especially when all of the builds are created on `prepublishOnly`.
~~I had trouble pushing this, I …
=> WIP: Git hooks

src/concatAll.js, src/index.d.ts, src/index.js, test/concatAll.js
=> feat: concatAll

src/index.d.ts
By doing #392, I noticed that `RA.appendFlipped` typescript signature was missing.
=> fix(appendFlipped): add curried typescript signature

.commitlintrc.json, package.json
commitlint now supports multiple cases for scopes, so this PR adds config to support either camelcase or kebabcase in a commit message's scope:
```
scope(functionName): foo
```
or
```
scope(example-value): foo
```
Closes #472
=> chore(commitlint): camel or kebab case for scope

src/index.d.ts, src/index.js, src/lengthEq.js, src/lengthGt.js, src/lengthGte.js, src/lengthLt.js, src/lengthLte.js, src/lengthNotEq.js, test/lengthEq.js, test/lengthGt.js, test/lengthGte.js, test/lengthLt.js, test/lengthLte.js, test/lengthNotEq.js
Adds remaining functions to test of list or string length is equal or notEqual to the supplied length.
Note: I'm unsure of the correct behaviour for `lengthNotEq` when the value supplied does not have a length property. I am returning false, but should we do something else?
Closes #444
=> feat: add lengthEq and lengthNotEq

package.json
This suppress deprecation warnings that were present before this update
=> chore(package): update eslint-config-airbnb-base to v13.1.0

src/index.d.ts, src/index.js, src/internal/polyfills/String.repeat.js, src/repeatStr.js, test/repeatStr.js
Ref #667
I made this consistent with https://ramdajs.com/docs/#repeat. The data seems to be the first argument and I suppose there is a reason for this. To make it truly functional without consulting ramda, I'd switch the order of the arguments. In FP the data should be always last.
=> feat: add repeatStr

src/index.d.ts, src/index.js, src/nand.js, test/nand.js
Tries to solve https://github.com/char0n/ramda-adjunct/issues/237
Note: While committing it, eslint-plugin-ramda had a bug, see https://github.com/ramda/eslint-plugin-ramda/pull/26, so I disabled this specific eslint rule in the configuration. Maybe I'm missing something.
=> Implement nand

test/async.js, test/ceil.js, test/compact.js, test/concatAll.js, test/concatRight.js
Batch 1
test/
- async.js
-   ceil.js
-   compact.js
-   concatAll.js
-   concatRight.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#1

test/divideNum.js, test/dropArgs.js, test/ensureArray.js, test/flattenPath.js, test/flattenProp.js
test/
- divideNum.js
- dropArgs.js
- ensureArray.js
- flattenPath.js
- flattenProp.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#3

test/isFalsy.js, test/isFinite.js, test/isFloat.js, test/isFunction.js, test/isGeneratorFunction.js, test/isInteger.js, test/isNegative.js
Batch 6
test/
- isFalsy.js
- isFinite.js
- isFloat.js
- isFunction.js
- isGeneratorFunction.js
- isInteger.js
- isNegative.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#6

test/isNotGeneratorFunction.js, test/isNotNil.js, test/isNotNull.js, test/isNotNumber.js, test/isNotObj.js, test/isNotObjLike.js, test/isNotPair.js
Batch 7
test/
- isNotGeneratorFunction.js
- isNotNil.js
- isNotNull.js
- isNotNumber.js
- isNotObj.js
- isNotObjLike.js
- isNotPair.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#7

test/isNotPlainObj.js, test/isNotRegExp.js, test/isNotString.js, test/isNotUndefined.js, test/isNotValidDate.js, test/isNotValidNumber.js, test/isNull.js
Batch 8
test/
- isNotPlainObj.js
- isNotRegExp.js
- isNotString.js
- isNotUndefined.js
- isNotValidDate.js
- isNotValidNumber.js
- isNull.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#8

test/isNumber.js, test/isObj.js, test/isObjLike.js, test/isOdd.js, test/isPair.js, test/isPlainObj.js, test/isPositive.js
Batch 9
test/
- isNumber.js
- isObj.js
- isObjLike.js
- isOdd.js
- isPair.js
- isPlainObj.js
- isPositive.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#9

test/isPromise.js, test/isRegExp.js, test/isString.js, test/isThenable.js, test/isTrue.js, test/isTruthy.js, test/isUndefined.js
Batch 10
test/
- isPromise.js
- isRegExp.js
- isString.js
- isThenable.js
- isTrue.js
- isTruthy.js
- isUndefined.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#10

test/lengthNotEq.js, test/lensEq.js, test/lensIso.js, test/lensNotEq.js, test/lensNotSatisfy.js, test/lensSatisfies.js, test/liftF.js
Batch 12
test/
- lengthNotEq.js
- lensEq.js
- lensIso.js
- lensNotEq.js
- lensNotSatisfy.js
- lensSatisfies.js
- liftF.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#12

test/liftFN.js, test/list.js, test/mapIndexed.js, test/mergePath.js, test/mergePaths.js, test/mergeProp.js, test/mergeProps.js
Batch 13
test/
- liftFN.js
- list.js
- mapIndexed.js
- mergePath.js
- mergePaths.js
- mergeProp.js
- mergeProps.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#13

test/mergeRight.js, test/move.js, test/neither.js, test/noneP.js, test/nonePass.js
Batch 14
test/
- mergeRight.js
- move.js
- neither.js
- noneP.js
- nonePass.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#14

test/padCharsEnd.js, test/padCharsStart.js, test/padEnd.js, test/pathNotEq.js, test/pathOrLazy.js
Batch 16
test/
- padCharsEnd.js
- padCharsStart.js
- padEnd.js
- pathNotEq.js
- pathOrLazy.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#16

test/paths.js, test/pickIndexes.js, test/propNotEq.js, test/reduceIndexed.js, test/reduceP.js
Batch 17
test/
- paths.js
- pickIndexes.js
- propNotEq.js
- reduceIndexed.js
- reduceP.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#17

test/reduceRightP.js, test/rejectP.js, test/renameKeys.js, test/renameKeysWith.js, test/repeatStr.js
Batch 18
test/
- reduceRightP.js
- rejectP.js
- renameKeys.js
- renameKeysWith.js
- repeatStr.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#18

test/resolveP.js, test/round.js, test/seq.js, test/sign.js, test/sliceFrom.js
Batch 19
test/
- resolveP.js
- round.js
- seq.js
- sign.js
- sliceFrom.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#19

test/sliceTo.js, test/spreadPath.js, test/spreadProp.js, test/stubArray.js, test/stubNull.js, test/stubObj.js, test/stubString.js
Batch 20
test/
- sliceTo.js
- spreadPath.js
- spreadProp.js
- stubArray.js
- stubNull.js
- stubObj.js
- stubString.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#20

test/Y.js, test/stubUndefined.js, test/subtractNum.js, test/trimEnd.js, test/trimStart.js, test/trunc.js, test/viewOr.js, test/weave.js, test/weaveLazy.js
Batch 21
test/
- stubUndefined.js
- subtractNum.js
- trimEnd.js
- trimStart.js
- trunc.js
- viewOr.js
- weave.js
- weaveLazy.js
- Y.js
=> test(files): Use chai directly instead of internal eq function in test asserts, B#21

test/fantasy-land/Identity.js, test/internal/ap.js, test/shared/eq.js
Batch 22
- test/fantasy-land/Identity.js
- test/internal/ap.js
It seems to me eq is eliminated from all files.
=> test(files): Use chai directly instead of internal eq function in test asserts, B#22

test/isNotPlainObj.js
Batch 5
@char0n, as I know the function must be curried to support Ramda placeholders. The isNotPlainObj function is a complement(isPlainObj). [isPlainObj](https://github.com/char0n/ramda-adjunct/blob/master/src/isPlainObj.js) looks like a normal arrow function, but placeholder works with it. I can't find a piece of code where isPlainObj was curried (or perhaps I missed something). May you please explain this to me?
=> test(isNotPlainObj): add ramda placeholder and make tests consistent

types/index.d.ts
before:
after:
When https://github.com/microsoft/TypeScript/pull/29317 lands, this will be able to be further improved to remove `false`, `0`, `""`, and `NaN`.  If you want to make an issue to check up on that when that happens please do.
=> Compact types

test/padCharsStart.js, test/padEnd.js, test/padStart.js, test/pathNotEq.js, test/pathOrLazy.js, test/paths.js, test/pickIndexes.js, test/propNotEq.js, test/reduceIndexed.js
Batch 21
Files:
test/
- padCharsStart.js
- padEnd.js
- padStart.js
- pathNotEq.js
- pathOrLazy.js
- paths.js
- pickIndexes.js
- propNotEq.js
- reduceIndexed.js
=> test: add ramda placeholder and make tests consistent

src/allEqual.js, src/allIdentical.js, src/allP.js, src/allSettledP.js, src/anyP.js
migrate from internal curry1 to standard curryN
first batch of 5:
src/allEqual.js
src/allIdentical.js
src/allP.js
src/allSettledP.js
src/anyP.js
Ref #1340
=> refactor(src): remove curry1 dependency

src/isNumber.js
replace _isNumber with:
const isNumber = R.pipe(R.type, R.identical('Number'));
Ref #1362
=> refactor(src): remove internal ramda dependency

src/index.js, src/thenCatchP.js, test/thenCatchP.js, types/index.d.ts, types/test/thenCatchP.ts
This PR deals with adding a new feature called `thenCatchP`.
#1233 
I wrote this for one of my own projects and thought I would take a crack at submitting it back to ramda-adjunct. I only wrote the one test because that was enough for me to feel confident in the functionality given such a simple abstraction that's already well covered by `R.invoker`'s tests.
Sorry in advance if I didn't follow other conventions
=> Added `thenCatchP`

types/index.d.ts, types/test/isIterable.ts
=> fix(iterable): Convert isIterable into a type guard function

src/lensTraverse.js
Add the link int lensTraverse.js  to access to  sequence section in the rambda  page
=> docs(comment): fix link to sequence page

types/index.d.ts, types/test/async.ts, types/test/cata.ts, types/test/compact.ts, types/test/concatAll.ts, types/test/concatRight.ts
Progress on #978
With this, all functions alphabetically from `allEqual` to `concatRight` are type tested. This also fixes wrong types for a curried version of `cata`
=> Add missing type tests

src/fantasy-land/Identity.js
Closes #1614
It is now working as expected.
As mentioned in [JSDoc `@private` page](https://jsdoc.app/tags-private.html),
> The `@private` tag marks a symbol as private, or not meant for general use. Private members are not shown in the generated output unless JSDoc is run with the `-p/--private` command-line option. In JSDoc 3.3.0 and later, you can also use the `-a/--access` command-line option to change this behavior.
=> fix Identity missing in documentation

src/index.js, src/renameKeyWith.js, test/renameKeyWith.js, types/index.d.ts, types/test/renameKeyWith.ts
Closes #1228
Hi there! Some questions:
1. I'm not sure I got the signature in the documentation correct, could you please check it? Currently it is `(a -> b) -> c -> {a: *} -> {b: *}`
2. I did two versions, one is a bit simpler (the latest commit), but the other one (before the latest commit) has the advantage of being stable when changing to an existing key name. Which one do you prefer?
3. For typing I just went with `object` as it is used for `renameKeysWith`, but actually I would prefer to limit the input to a `Record` and then limit the key to be a key of said record. The more complicated version has the disadvantage that it relies on `mergeRight` which we would have to use from `ramda-adjunct` even though it is deprecated to keep compatibilty with older `ramda` versions that do not …
=> Add renameKeyWith

types/index.d.ts
isNotEmpty was removed in #2983 but this type declaration was not. This results in language servers reporting that isNotEmpty is available when it is not.
Closes #3071
=> fix(types): remove isNotEmpty type declaration

src/isMap.js
fix typo err in  isMap.js example.
=> docs(isMap): typo err in example
