README.md
package-lock.json
package.json
src/index.d.ts
src/index.js
src/mergeProps.js
test/mergeProps.js

Ref https://github.com/ramda/ramda/issues/2295

feat: add mergeProps

---

src/mergePaths.js
src/mergeProps.js

use curryN in mergePaths and mergeProps implementation

feature (curryN-in-mergeProps-and-mergePaths)

---

.codeclimate.yml

ci(codeclimate): add custom codeclimate settings

---

src/index.d.ts
src/index.js
src/mergePath.js
src/mergePaths.js
src/mergeProp.js
test/mergePath.js
test/mergeProp.js

https://github.com/char0n/ramda-adjunct/issues/147
https://github.com/ramda/ramda/issues/2255

added mergePath, mergeProp, changed argument names in mergePaths and mergeProps

---

src/index.d.ts
src/index.js
src/isNotPair.js
src/isPair.js
test/isNotPair.js
test/isPair.js

feat: add isPair, isNotPair

---

src/isArray.js

refactor(isArray): use Array.isArray if available

---

src/index.d.ts
src/index.js
src/isPromise.js
test/isPromise.js
test/isString.js

feat: add isPromise

---

src/index.d.ts
src/index.js
src/isTruthy.js
test/isTruthy.js
test/shared/Symbol.js

feat: add isTruthy

---

src/defaultWhen.js
src/index.d.ts
src/index.js
test/defaultWhen.js

feat: add defaultWhen

---

src/Y.js
src/index.d.ts
src/index.js
test/Y.js

feat: add Y combinator

---

package.json
src/allP.js
src/index.d.ts
src/index.js
src/reduceP.js
src/reduceRightP.js
src/rejectP.js
test/.eslintrc
test/allP.js
test/mocha-bootstrap.js
webpack.config-test.web.js

feat: add allP

---

src/index.d.ts
src/index.js
src/neither.js
test/neither.js

Add `neither` which is a complement of Ramda's `either`.
Ref #234

feat: add neither

---

src/seq.js

docs(seq): add composition usage example

---

src/index.d.ts
src/index.js
src/isNonEmptyArray.js
test/isNonEmptyArray.js

feat: add isNonEmptyArray

---

src/index.d.ts
src/index.js
src/pathNotEq.js
test/pathNotEq.js
test/propNotEq.js

feat(#217): add pathNotEq

---

src/index.d.ts
src/index.js
src/isEmptyString.js
test/isEmptyString.js

feat: add isEmptyString

---

src/index.d.ts
src/index.js
src/isNonEmptyString.js
test/isNonEmptyString.js

feat: add isNonEmptyString

---

.eslintignore

chore(eslint): Add tmp-test-bundle.js in .gitignore file

---

package.json
test/.eslintrc
test/concatRight.js
test/isArrayLike.js
test/isNotArrayLike.js
test/isPromise.js
test/mergeRight.js
test/pathNotEq.js
test/propNotEq.js
test/typescript.js

style(tests): add mocha specific rules

---

src/index.d.ts
test/notAllPass.js

Some minor corrections. Just whitespace and one correction for a describe block name.

Minor Style Corrections

---

src/index.d.ts
src/index.js
src/nonePass.js
test/nonePass.js

Adds complement of Ramda's anyPass
Ref: #234

feat(nonePass): Add complement of Ramda’s anyPass

---

src/compact.js
src/index.d.ts
src/index.js
test/compact.js

feat: add compact

---

README.md

- Fix issues with grammar.
- Fix inconsistent punctuation.
- Minor improvements to the copy to clarify meaning.
- Remove hard linebreaks causing text to wrap at 100 chars.

docs(README): Fix grammar, improve copy and remove hard breaks

---

test/isPromise.js
test/isThenable.js

should catch rejected promises in tests.
closes #264.

test: fix UnhandledPromiseRejectionWarning

---

package.json

add `npm run docs` after `npm run build`

chore(package): improve prepublishOnly script

---

src/index.d.ts
src/mergeRight.js

fix: RA.defaults not exported

---

package.json
src/index.d.ts
tslint.json

- Install `tslint@5.9.1` (devDependencies)
- Start `tslint` when ` npm run lint`
- Start `tslint (fix mode)` when `npm run lint:fix`
- Add basic `tslint.json` config file
- Fix lint errors in `src/index.d.ts`
Closes #340 
Feel free to feedback about the `tslint` configuration file.

Add tslint

---

.codeclimate.yml
src/index.d.ts
src/index.js
src/mapIndexed.js
test/mapIndexed.js

Closes #282
I need review from this one, are there enough tests ?
Someone can check my signature types ? (maybe @BjornMelgaard )
I will wait for this review before I start to implement #281 
@char0n, @Undistraction, @rockymadden

feat: add mapIndexed

---

src/appendFlipped.js
src/index.d.ts
src/index.js
test/appendFlipped.js

Adds a version of Ramda's append with the argument order flipped.
closes #333

feat(appendFlipped): add flipped version of append

---

src/index.d.ts
src/index.js
src/reduceIndexed.js
test/reduceIndexed.js

feat: add reduceIndexed

---

package.json

chore(scripts): change ramda:test launch order

---

.eslintrc
test/isBoolean.js
test/isNotBoolean.js
test/seq.js
test/stubArray.js
test/stubObj.js

+ fix errors according to this new eslint rules (in 5 tests files)
Closes #377

style(eslint): add newlines-between option to import/order rule

---

src/index.d.ts
src/index.js
src/omitBy.js
test/omitBy.js

Resolves #171.
Because I don't have experience writing tests, they're based on [Ramda's tests of `pickBy`](https://github.com/ramda/ramda/blob/v0.25.0/test/pickBy.js).

Adds RA.omitBy

---

src/internal/ap.js
src/isNilOrEmpty.js
src/isObj.js

refactor: change anyPass to either where appropriate

---

src/dispatch.js
src/index.d.ts
src/index.js
test/dispatch.js

Ref #66
See the tests for usage. I'll add the required docs if we agree this is something we want. I personally have many usecase for this. See #66 for more info. It was proposed originaly by Michael Fogus.

feat: add dispatch

---

src/index.d.ts
src/index.js
src/isNegative.js
src/isNonNegative.js
src/isNonPositive.js
src/isPositive.js
test/isNonNegative.js
test/isNonPositive.js

Add predicates for testing numbers for being non-positive (zero and all negative numbers) or non-negative (zero and all positive numbers)
Closes #324

Add isNonPositive and isNonNegative

---

README.md

Quick stop-gap reorganisation of README to make easier for new users to find what they need.

docs(readme): reorder sections and minor rewrites

---

src/appendFlipped.js
src/concatAll.js
src/concatRight.js
src/curryRight.js
src/curryRightN.js
src/defaultWhen.js
src/hasPath.js
src/index.d.ts
src/isNilOrEmpty.js
src/isNotEmpty.js
src/isNotNil.js
src/isNotPair.js
src/isPair.js
src/lensIso.js
src/liftFN.js
src/mergeRight.js
src/neither.js
src/nonePass.js
src/notAllPass.js
src/notBoth.js
src/omitIndexes.js
src/pathNotEq.js
src/paths.js
src/pickIndexes.js
src/propNotEq.js
src/reduceP.js
src/seq.js
src/sliceFrom.js
src/sliceTo.js
src/viewOr.js

in ramdajs.com/docs links
Closes #470

docs: add missing R. prefix in documentation

---

src/index.d.ts
src/index.js
src/lensTraverse.js
test/lensTraverse.js

This is POC that traversables can be manipulated via lenses.
This is the [draft of the article](https://www.linkedin.com/pulse/draft/AgGMpHfWPg0aewAAAWLLKtT0R_vAWCIYJMoOR678o56W2vY2_obPLeesnSWdIiPQwQduu30) that I created during the process of creating `RA.lensTraverse`. The last part of `Real World Applications` is still unfinished. Pls feel free to provide review even for the article.
https://www.linkedin.com/pulse/draft/AgGMpHfWPg0aewAAAWLLKtT0R_vAWCIYJMoOR678o56W2vY2_obPLeesnSWdIiPQwQduu30

feat: add traversable lenses

---

README.md

docs(README.md): fix RA E56 imports

---

package.json

chore(package): update tslint-config-prettier to version 1.12.0

---

src/contained.js
src/index.d.ts
src/index.js
test/contained.js

feat: add contained

---

package.json

- Keywords needs to be an array of strings but was a string
- Fix leading whitespace in Guillaume ARM's contributor email address

Fix package.json keywords

---

src/allP.js
src/index.d.ts
src/index.js
src/thenP.js
test/thenP.js

feat: add thenP

---

src/curryRight.js

I think that signature for `curryRight` currently is not valid, so I've update it to match.
P.S. 
I am just learning FP, so I may be wrong.

Update signature for curryRight

---

src/move.js

docs(move): add missing param and refactor others

---

.eslintrc
test/lengthEq.js
test/lengthGt.js
test/lengthGte.js
test/lengthLt.js
test/lengthLte.js
test/lengthNotEq.js
test/move.js

Apply new rule enforcing use of single quotes except where using doubles would prevent need to escape singles. 
Closes #553

style(eslint): enforce single quotes

---

src/concatAll.js

docs(concat-all): using csl for @see tag

---

package.json

After experimenting with the npms search, I think both utils and utilities are worth adding.
Closes #555

build(package): add ‘utils’ and ‘utilities’ keywords

---

src/allEqual.js
src/allP.js
src/index.d.ts
src/index.js
test/allEqual.js

Continuation of https://github.com/char0n/ramda-adjunct/pull/513

feat: add allEqual

---

src/inRange.js

This fixes a small typo in the documentation, no code changes
The commit
No testing required
- Does this require a blog post? No
- Does this require a knowledge base update? No
- Does support need training for this? No
- Does this has to be communicated to partners? No

Typo in paramater documentation

---

src/liftF.js

docs(liftF): fix jsdoc description

---

README.md
package.json

making the main sentence consistent across the repo
Closes #591

docs: change main ramda-adjunct description sentense

---

LICENSE.md

https://opensource.org/licenses/BSD-3-Clause
Closes #645

chore(LICENSE): use uptodate BSD 3-Clause License template

---

src/dropArgs.js
src/index.d.ts
src/index.js
test/dropArgs.js

feat: add dropArgs

---

LICENSE.md

https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/
I changed the copyright notice to give me less prominence and to explicitly include everybody that ever contributed to the project. IMHO that's legally more correct than having my name there only.

chore(LICENSE): change copyright notice to include every RA contributor

---

.npmignore

chore: remove unneded doc files from npm distribution

---

src/allIdentical.js
src/index.d.ts
src/index.js
test/allIdentical.js

feat: add allIdentical

---

src/allIdenticalTo.js
src/index.d.ts
src/index.js
test/allIdenticalTo.js

feat: add allIdenticalTo

---

src/allEqualTo.js
src/index.d.ts
src/index.js
test/allEqualTo.js

feat: add allEqualTo

---

src/index.d.ts

Hi, 
This PR just add some typescript typing to seq function, in order to use it curried.
Thanks for you work.
Matt'

Add curring typing to seq function.

---

src/isRegExp.js

fix(isRegExp): make this predicate work in different realms

---

src/isBoolean.js

fix(isBoolean): make this predicate work in different realms

---

src/isDate.js

fix(isDate): make this predicate work in different realms

---

src/isAsyncFunction.js
src/isFunction.js
src/isGeneratorFunction.js

refactor: use R.type where appropriate

---

.circleci/config.yml
README.md

ci(circleci): test RA on node 8, 9, 10, 11

---

LICENSE.md

Formalization done according to: https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/

docs(LICENSE): formalize copyright notice

---

src/isAsyncFunction.js
test/isAsyncFunction.js

Also tests made consistent.
Ref #624

feat(isAsyncFunction): add support for ramda placeholder

---

src/isBoolean.js
test/isBoolean.js

Also tests made consistent
Ref #624

feat(isBoolean): add ramda placeholder support

---

src/index.d.ts
src/index.js
src/round.js
test/round.js

feat: add round

---

src/ceil.js
src/index.d.ts
src/index.js
test/ceil.js

feat: add ceil

---

src/floor.js
src/index.d.ts
src/index.js
test/floor.js

feat: add floor

---

src/ceil.js
src/index.d.ts
src/index.js
src/internal/polyfills/Math.trunc.js
src/round.js
src/trunc.js
test/trunc.js

feat: add trunc

---

src/lengthGte.js

docs(lengthGte): fix documentation example

---

src/index.d.ts
src/index.js
src/internal/polyfills/Math.sign.js
src/sign.js
test/sign.js

feat: add sign

---

src/async.js
src/index.d.ts
src/index.js
test/async.js

feat(async): add initial implementation

---

src/index.d.ts

fix(typings): remove accidental import

---

src/index.d.ts
src/index.js
src/replaceAll.js
test/replaceAll.js

feat: add replaceAll

---

src/isNegative.js
src/isNilOrEmpty.js
test/ensureArray.js
test/flattenPath.js
test/flattenProp.js
test/inRange.js
test/isNegative.js
test/isNilOrEmpty.js

More info here: https://github.com/char0n/ramda-adjunct/issues/624

Ramda placeholder support + more tests consistency

---

src/isNonNegative.js
test/isNonEmptyArray.js
test/isNonEmptyString.js
test/isNonNegative.js

For more info see: https://github.com/char0n/ramda-adjunct/issues/624

Ramda placeholder support + tests consistency

---

test/isNotEmpty.js

test(isNotEmpty): make tests consistent

---

src/allP.js
src/allSettledP.js
src/index.d.ts
src/index.js
src/internal/polyfills/Promise.allSettled.js
test/allSettledP.js

https://github.com/char0n/ramda-adjunct/issues/761

allSettledP

---

src/index.d.ts
src/index.js
src/isNotNilOrEmpty.js
test/isNotNilOrEmpty.js

Hey,
This PR  add `isNotNilOrEmpty` 
#70

feat: adding isNotNilOrEmpty

---

package.json

docs(search): fix search functionality

---

src/index.d.ts

fix(mergePath) Fix TS typing for mergePath

---

src/index.d.ts
src/index.js
src/isIterable.js
test/isIterable.js

closes #351
I'm not sure why, but at least on my end I'm getting an error that `IterableIterator` is unknown, but it should be as far as I can tell:
https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2015.iterable.d.ts
either way, let me know what you think.

feat: add isIterable

---

test/isIterable.js

test(isIterable): make tests consistent with rest of codebase

---

package-lock.json
package.json
webpack.config.js

build(umd): replace uglify with terser

---

src/pickIndexes.js

Solves https://github.com/char0n/ramda-adjunct/issues/189
If you have any additional questions please don't hesitate to contact any of the core commiters.

Expand pickIndexes documentation

---

src/flattenDepth.js
src/index.d.ts
src/index.js
test/flattenDepth.js

Closes https://github.com/char0n/ramda-adjunct/issues/844

Feat: add flattenDepth

---

src/flattenDepth.js
test/flattenDepth.js

test(flattenDepth): make tests more declarative

---

.circleci/config.yml
webpack.config.js

ci(circleci): add support for testing on node 12.y.z

---

.npmignore
types/index.d.ts
types/test.ts
types/test/allEqual.ts
types/test/allEqualTo.ts
types/test/allIdentical.ts
types/test/allIdenticalTo.ts
types/test/allP.ts
types/test/allSettledP.ts

test(typings): add initial tests

---

SECURITY.md

docs(SECURITY): create draft of security policies

---

src/nand.js
test/nand.js

test(nand): make tests and documentation consistent

---

src/nand.js
types/index.d.ts

Nand currently has a wrong documentation, see https://en.wikipedia.org/wiki/NAND_gate
If you have any additional questions please don't hesitate to contact any of the core commiters.

docs: Fix documentation of nand

---

src/index.js
src/nor.js
test/nor.js
types/index.d.ts

Implements https://github.com/char0n/ramda-adjunct/issues/285
If you have any additional questions please don't hesitate to contact any of the core commiters.

feat(logic): Implement nor

---

src/index.js
src/isSparseArray.js
test/isSparseArray.js
types/index.d.ts
types/test/isSparseArray.ts

feat(type): add isSparseArray predicate

---

src/escapeRegExp.js
src/index.js
test/escapeRegExp.js
types/index.d.ts
types/test/escapeRegExp.ts

feat(string): add escapeRegExp

---

src/index.js
src/isSymbol.js
test/isSymbol.js
types/index.d.ts
types/test/isSymbol.ts

feat(symbol): add isSymbol

---

src/anyP.js
src/index.js
src/internal/polyfills/Promise.any.js
test/anyP.js
types/index.d.ts
types/test/anyP.ts

feat(promise): add anyP

---

types/test/appendFlipped.ts

Ref https://github.com/char0n/ramda-adjunct/issues/978

test(appendFlipped): add tests for typescript typings

---

types/index.d.ts
types/test/argsPass.ts

test(argsPass): add tests for typescript typings

---

types/index.d.ts
types/test/allEqual.ts
types/test/allEqualTo.ts
types/test/allIdentical.ts
types/test/allIdenticalTo.ts
types/test/allP.ts
types/test/allSettledP.ts
types/test/anyP.ts
types/test/appendFlipped.ts
types/test/divideNum.ts
types/test/escapeRegExp.ts
types/test/helpers/index.ts
types/test/isSparseArray.ts
types/test/subtractValue.ts

test(typings): standardize the way how we do tests

---

src/index.js
src/pathOrLazy.js
test/pathOrLazy.js
types/index.d.ts
types/test/pathOrLazy.ts

https://github.com/char0n/ramda-adjunct/issues/1084

feat(object): add pathOrLazy

---

types/test/ceil.ts

test(ceil): add tests for typescript typings

---

src/argsPass.js
src/dispatch.js

Things needs to ge constructed first before they are exported.
Closes #1092

refactor: make default export consistent

---

src/index.js
src/internal/polyfills/Array.from.js
src/toArray.js
test/toArray.js
types/index.d.ts
types/test/toArray.ts

feat: add toArray #342

---

src/allUnique.js
src/index.js
test/allUnique.js
types/index.d.ts
types/test/allUnique.ts

Hi @char0n, I gave a try at this issue #515, hope you don't mind. Also, should I use the same PR for `allUnique` and `notAllUnique`?

feat(list): add allUnique #515

---

src/index.js
src/isSet.js
test/isSet.js
types/index.d.ts
types/test/isSet.ts

feat(type): add isSet

---

src/index.js
src/isNegativeZero.js
test/isNegativeZero.js
types/index.d.ts
types/test/isNegativeZero.ts

feat(type): add isNegativeZero

---

src/index.js
src/isMap.js
test/isMap.js
types/index.d.ts
types/test/isMap.ts

feat(type): add isMap

---

src/index.js
src/internal/polyfills/Number.isSafeInteger.js
src/isSafeInteger.js
test/isSafeInteger.js
types/index.d.ts
types/test/isSafeInteger.ts

feat(type): add  isSafeInteger

---

src/index.js
test/anyP.js
types/index.d.ts
types/test/anyP.ts

Closes https://github.com/char0n/ramda-adjunct/issues/815

feat(function): add firstP alias for anyP

---

src/index.js
src/notAllUnique.js
test/notAllUnique.js
types/index.d.ts
types/test/notAllUnique.ts

feat(list): add notAllUnique #515

---

src/index.js
src/internal/polyfills/String.padCharsEnd.js
src/padCharsEnd.js
test/padCharsEnd.js
types/index.d.ts
types/test/padCharsEnd.ts

feat(string): add padCharsEnd

---

src/index.js
src/internal/polyfills/String.trimEnd.js
src/trimEnd.js
test/trimEnd.js
types/index.d.ts
types/test/trimEnd.ts

feat(string): add trimEnd #808

---

src/internal/polyfills/String.replaceAll.js
src/replaceAll.js
test/replaceAll.js
types/index.d.ts
types/test/replaceAll.ts

fix(replaceAll): add TC39 proposal-compliant String.replaceAll ponyfill to use in RA.replaceAll 

---

src/index.js
src/padEnd.js
test/padEnd.js
types/index.d.ts
types/test/padEnd.ts

feat(string): add padEnd

---

src/index.js
src/unzipObjWith.js
test/unzipObjWith.js
types/index.d.ts
types/test/unzipObjWith.ts

feat(object): add unzipObjWith

---

test/appendFlipped.js

test(appendFlipped): Use chai directly instead of internal eq function in test asserts

---

package-lock.json
package.json
types/tslint.json

chore(package): update dtslint to version 1.0.2

---

test/mocha-testem.mustache
test/padCharsEnd.js
test/repeatStr.js
test/replaceAll.js
test/sign.js
test/trimEnd.js
test/trimStart.js
test/trunc.js
testem.json

test(replaceAll): make tests consistent with other string functions

---

src/index.js
src/internal/polyfills/String.padStart.js
src/padCharsStart.js
test/padCharsStart.js
types/index.d.ts
types/test/padCharsStart.ts

feat(string): added padCharsStart function

---

test/floor.js
test/hasPath.js
test/inRange.js
test/isArray.js
test/isArrayLike.js

Batch 4
test/
- floor.js
- hasPath.js
- inRange.js
- isArray.js
- isArrayLike.js

test(files): Use chai directly instead of internal eq function in test asserts, B#4

---

test/isAsyncFunction.js
test/isBoolean.js
test/isDate.js
test/isEmptyArray.js
test/isEmptyString.js
test/isEven.js
test/isFalse.js

Batch 5
test/
- isAsyncFunction.js
- isBoolean.js
- isDate.js
- isEmptyArray.js
- isEmptyString.js
- isEven.js
- isFalse.js

test(files): Use chai directly instead of internal eq function in test asserts, B#5

---

.gitignore
src/delayP.js
src/index.js
test/delayP.js
types/index.d.ts
types/test/delayP.ts

feat(promise): add delayP

---

package-lock.json
package.json
src/delayP.js
test/delayP.js
types/index.d.ts
types/test/delayP.ts

refactor(delayP): perform cleanup

---

test/isValidDate.js
test/isValidNumber.js
test/lengthEq.js
test/lengthGt.js
test/lengthGte.js
test/lengthLt.js
test/lengthLte.js

Batch 11
test/
- isValidDate.js
- isValidNumber.js
- lengthEq.js
- lengthGt.js
- lengthGte.js
- lengthLt.js
- lengthLte.js

test(files): Use chai directly instead of internal eq function in test asserts, B#11

---

test/nonePass.js
test/noop.js
test/notAllPass.js
test/notBoth.js
test/omitBy.js
test/omitIndexes.js

Batch 15
test/
- noop.js
- notAllPass.js
- notBoth.js
- omitBy.js
- omitInIndexes.js

test(files): Use chai directly instead of internal eq function in test asserts, B#15

---

package.json

Add new collaborator

---

test/isNotNull.js

Ref #624
Batch 0
test/isNotNull.js

test(files): add ramda placeholder and make tests consitent, B0

---

package-lock.json
package.json

chore(package): update eslint-plugin-import to v2.19.1

---

src/isObj.js
test/isNotObj.js

test(isNotObj): add ramda placeholder and make tests consitent

---

src/isObjLike.js
test/isNotObj.js
test/isNotObjLike.js

test(isNotObjLike): add ramda placeholder and make tests consistent

---

src/isPair.js
test/isNotPair.js

test(isNotPair): add ramda placeholder and make tests consistent

---

src/isValidDate.js
test/isNotRegExp.js
test/isNotString.js
test/isNotUndefined.js
test/isNotValidDate.js

Batch 6
Files:
test/
- isNotRegExp.js
- isNotString.js
- isNotUndefined.js
- isNotValidDate.js
src/
- isValidDate.js (curry1)

test: add ramda placeholder and make tests consistent

---

package-lock.json
package.json

chore(package): update dtslint to version 2.0.3

---

package-lock.json
package.json

chore(package): update dtslint to 2.0.4 version

---

src/internal/polyfills/String.trimEnd.js
src/internal/polyfills/String.trimStart.js

refactor: add more precise trimming

---

src/index.js
src/trimCharsStart.js
test/trimCharsStart.js
types/index.d.ts
types/test/trimCharsStart.ts

#1135 
Add trimCharsStart function / types / tests. Happy to receive any feedback 🙇

feat: add trimCharsStart

---

src/index.js
src/trimCharsEnd.js
src/trimCharsStart.js
test/trimCharsEnd.js
types/index.d.ts
types/test/trimCharsEnd.ts

#1136
Add trimCharsEnd / types / tests. Also update a couple of comments for trimCharsStart to make the wordings more consistent.

feat: add trimCharsEnd

---

src/index.js
src/padStart.js
test/padStart.js
types/index.d.ts
types/test/padStart.ts

#1103
Add padStart / types / tests

feat: add padStart

---

package.json

chore: add support for ramda 0.27.0

---

test/concatAll.js

Closes https://github.com/char0n/ramda-adjunct/issues/409

test(concatAll): uncomment test testing non-compatible semigroups

---

package-lock.json
package.json

chore(package): update dtslint to version 2.0.6

---

package-lock.json
package.json

chore(package): update dtslint to version 3.0.0

---

src/index.js
src/sortByProps.js
test/sortByProps.js
types/index.d.ts
types/test/sortByProps.ts

Addresses #1242.
I've written the function based on the ramda cookbook and wrote tests

Add sort by props func

---

types/index.d.ts
types/test/mapIndexed.ts

Closes https://github.com/char0n/ramda-adjunct/issues/1330

fix(mapIndexed): Make list argument Readonly

---

src/index.js
src/isIndexed.js
test/isIndexed.js
types/index.d.ts
types/test/isIndexed.ts

Add `isIndexed`. Addresses https://github.com/char0n/ramda-adjunct/issues/1236

Is indexed

---

src/async.js
src/ceil.js
src/floor.js
src/isArray.js
src/isArrayLike.js

migrate from internal curry1 to standard curryN
second batch of 5:
src/async.js
src/ceil.js
src/floor.js
src/isArray.js
src/isArrayLike.js
Ref #1340

refactor(src): remove curry1 dependency

---

src/isString.js

replace _isString with:
R.pipe(R.type, R.identical('String'));
Ref #1360

refactor(src): remove internal ramda dependency

---

src/isArray.js

replace _isArray with:
R.pipe(R.type, R.identical('Array'))
Ref #1363

refactor(src): remove internal ramda _isArray

---

src/isPlainObj.js

replace internal ramda _isObject
Ref #1361

refactor(src): remove internal ramda reference

---

package-lock.json
package.json
types/tsconfig.json

chore(package): update dtslint to version 3.4.0

---

.circleci/config.yml

[#1154](https://github.com/char0n/ramda-adjunct/issues/1154)

chore(circleci): remove Node 8 testing

---

.circleci/config.yml

[#1410](https://github.com/char0n/ramda-adjunct/issues/1410)

chore(circleci): remove node 9 testing

---

.circleci/config.yml

[#1153](https://github.com/char0n/ramda-adjunct/issues/1153)

Test on Node version 13

---

src/index.js
src/invokeArgs.js
test/invokeArgs.js
types/index.d.ts
types/test/invokeArgs.ts

@char0n, I consider this as a draft PR. It seems to me everything works as expected, but I'm unsure about some things (for example, I don't know is it right to use "category Object", etc.). So, I'm waiting for your review and I'm ready to refine this PR.

feat(type): add invokeArgs

---

.circleci/config.yml

[#1442](https://github.com/char0n/ramda-adjunct/issues/1442)

test on Node 14

---

src/index.js
src/toInteger32.js
test/toInteger32.js
types/index.d.ts
types/test/toInteger32.ts

feat(toInteger32): add toInteger32

---

.dependabot/config.yml
.github/dependabot.yml

chore(dependabot): update dependabot config to v2

---

src/index.js
src/isNaturalNumber.js
test/isNaturalNumber.js
types/index.d.ts
types/test/isNaturalNumber.ts

Closes https://github.com/char0n/ramda-adjunct/issues/1440

isNaturalNumber

---

.github/workflows/merge-me.yaml

ci(deps): add automatic merge GA

---

src/index.js
src/rangeStep.js
test/rangeStep.js
types/index.d.ts
types/test/rangeStep.ts

feat(list): add rangeStep

---

src/index.js
src/overlaps.js
test/overlaps.js
types/index.d.ts
types/test/overlaps.ts

feat(relation): add overlaps

---

package-lock.json
package.json
src/fnull.js
src/internal/makeFlat.js
src/isSymbol.js
src/pathOrLazy.js

chore(deps-dev): bump eslint-config-prettier from 6.15.0 to 7.1.0

---

src/index.js
src/isSentinelValue.js
test/isSentinelValue.js
types/index.d.ts
types/test/isSentinelValue.ts

This PR adds a predicate to determine if a value is a sentinel value. #793

Add isSentinelValue

---

package-lock.json
package.json

chore(deps-dev): bump @babel/preset-env from 7.12.11 to 7.14.1

---

package-lock.json
package.json
src/internal/ponyfills/Promise.allSettled.js
test/flattenDepth.js
test/internal/ap.js
test/mapIndexed.js
test/paths.js
test/reduceP.js
test/reduceRightP.js

chore(deps-dev): bump prettier from 2.2.1 to 2.3.0

---

.circleci/config.yml
package-lock.json
package.json

Remove node 10 as this version was EOL on 30.4.2021

ci: add node 16 workflows

---

package-lock.json
package.json

chore(deps-dev): bump sinon from 10.0.1 to 11.1.1

---

README.md
package.json

feat: add support for ramda@0.27.2

---

package-lock.json
package.json
webpack.config-test.web.js

chore(deps-dev): bump sinon from 11.1.2 to 13.0.1

---

package.json
types/index.d.ts
types/test/isMap.ts
types/test/isNotMap.ts
types/test/renameKeys.ts
types/test/sortByPaths.ts

Co-authored-by: Andreas Herd (@mendrik) <mendrik76@gmail.com>
Refs #2354

refactor(types): change signature for renameKeys

---

src/isGeneratorFunction.js

Resolves CSP issue with new Function constructor.

fix(isGeneratorFunction): remove legacy predicate

---

package-lock.json
package.json
webpack.config-test.web.js

chore(deps-dev): bump glob from 8.1.0 to 9.0.2

---

package-lock.json
package.json

npm audit fix was run as well.

chore(deps-dev): remove unused development dependencies

---

types/index.d.ts

Refs 2c943fe3990ce5c4397112e8ba1197fe850c63af

fix(types): fix bug in typings that was causing downstream issues

---

package-lock.json
package.json
src/lensTraverse.js
types/test/allP.ts

chore(deps-dev): bump prettier from 3.0.3 to 3.2.5

---

.github/workflows/nodejs.yaml

ci(nodejs): use latest codecov action version (v4)

---

.husky/commit-msg
.husky/pre-commit
package-lock.json
package.json

chore(deps-dev): bump husky from 8.0.3 to 9.0.11

---

.github/dependabot.yml

ci(dependabot): update GitHub Actions

---

.github/dependabot.yml
.github/workflows/merge-me.yaml
.github/workflows/nodejs.yaml

ci: switch all jobs to Node.js@22

---

src/mergeProp.js

`p` was defined as array, but should be string.

docs(mergeProp): fix docs for p argument
